### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by thr44pw00d** [mstrosaker/fragrecruit#3]
Hi,
I've been trying fragrecruit with one genome and a sam-file produced by Bowtie2, and got the following error:

> Processing reference genome: 2608710259
> Traceback (most recent call last):
>   File "./fragplot", line 357, in <module>
>     for frag in frag_func(file):
>   File "/domus/h1/matthih/bin/fragrecruit/SAMFile.py", line 99, in SAMFile
>     yield SAMFragment(line)
>   File "/domus/h1/matthih/bin/fragrecruit/SAMFile.py", line 29, in __init__
>     self.location = int(fields[3])
> IndexError: list index out of range

Content of my config file:

```
microbiome = "Aci1"
shortname = "Aci1_vs_Kaiv"
basepath = "/proj/uppstore2017229/projects/matthias/bowtie2/bowtie2_Aci1_vs_Kaiv/"
refgenomes = [
    (
        "2608710259",
        "00000",
        "Kaiv-W7.fasta"
    )
]
samples = [
    (
        "Sample 1 (f, 31)",
        {
            "00000": "Aci1_vs_Kaiv.sam",
        }
    )
]
```

Command:
`./fragplot Aci_vs_Kaiv.config`

Do you know what the problem might be?

Thank you!

Regards,
Matthias

**Comment by thr44pw00d** [comment]
I guess the repository is not maintained anymore... ?
